research_task:
  description: >
    Conduct thorough research on {company} and the {job} role.
    A SUMMARY HAS ALREADY BEEN PROVIDED: {summary}
    Collect detailed information including:
    - Company Overview and Name
    - Company Mission and Vision (including strategic goals)
    - Market Position and Financial Metrics
    - Job Title and Key Responsibilities
    - Required Skills for the {job} role
    - Interview Experiences and sample technical questions (e.g., LeetCode questions)
    Use up-to-date sources to extract 10 key bullet points.
  expected_output: >
    A list of 10 bullet points summarizing key findings about {company} and the {job} role,
    covering aspects such as Company Name, Company Mission and Vision,
    Job Title, Key Responsibilities, Required Skills, Interview Experiences, and Example LeetCode Questions.
  agent: researcher

reporting_task:
  description: >
    - Provide a comprehensive summary about {company} and the job position {job}. Gather the following information:
        1. **Job Description:**
            - Search LinkedIn, the Company Career Site, Indeed, and Glassdoor for the job posting details.
        2. **Salary/Pay Range:**
            - Search http://levels.fyi/ for details on the salary range for {job} at {company}.
        3. **Interview Process:**
            - Gather insights from interview process reviews.
            - Identify whether the technical interviews are more focused on algorithms or data structures.
            - Explicity specify the range of total number of rounds, breaking them down into behavioral and technical rounds.
            - Include the typical overall duration of the interview process.
        4. **Interview Experience:**
            - Find an example of an interview experience for {job} at {company}.
        5. **Recommended Preparation:**
            - Search Reddit and Leetcode for recommended Leetcode problems for {company}.
  expected_output: >
    - Output a JSON object in the following format, and do not include any additional text or markdown:

            {{
                "company": "{company}",
                "results": {{
                    "job_description": {{
                    "status": "<Validated|Needs Work|Incorrect>",
                    "content": "List<Concise summary of the job posting>",
                    "source": ["<url1>", "<url2>", ...]
                    }},
                    "pay_range": {{
                    "status": "<Validated|Needs Work|Incorrect>",
                    "content": " List<Details on the salary range>",
                    "source": ["<url1>", "<url2>", ...]
                    }},
                    "interview_process": {{
                    "status": "<Validated|Needs Work|Incorrect>",
                    "content": "List <Details on the interview process, including round counts (behavioral and technical) and overall duration>",
                    "source": ["<url1>", "<url2>", ...]
                    }},
                    "example_interview_experience": {{
                    "status": "<Validated|Needs Work|Incorrect>",
                    "content": "List<Example of an interview experience>",
                    "source": ["<url1>", "<url2>", ...]
                    }}
                }}
            }}
  agent: reporting_analyst
